### ISSUE TITLE
repository_specification.py does not recognize GitHub token URLs

### ISSUE THREAD

**Issue by ayrton04** [ros-infrastructure/rosdistro#93]
We're seeing a lot of messages like this in the rosdistro cache jobs:

```
DEBUG:rosdistro:Skipped "github_manifest_provider()": VCS url "https://<token>@github.com/blah/blah.git" does not match expected format.
```

I believe the offending regex is here:
https://github.com/ros-infrastructure/rosdistro/blob/2bb8505ec0bdfcc57d7b2a1033235eb3ce21f9f2/src/rosdistro/repository_specification.py#L40

**Comment by dirk-thomas** [comment]
Your URL with the token is not one of the allowed URLs which are being tested in https://github.com/ros-infrastructure/rosdistro/blob/master/test/test_repository_specification.py Therefore I am not surprised that it doesn't pass the regex. Maybe @mikepurvis can comment on this since he added the stricter regex in #79.

**Comment by mikepurvis** [comment]
That can be added to the regex without too much trouble. I didn't realize it was possible to use a personal access token like that with Github HTTPS URLs, but that seems a reasonable alternative to SSH urls. Perhaps better even, since it allows anyone with a copy of the rosdistro to get read access to all the repos without them needing to have anything explicitly set up.

The only hiccup is that adding a new match group for the token/username is going to change the tuple which comes back from `get_url_parts`, either that or we include the token as part of the "domain" portion of it, meaning that the manifest provider match checks need to change from equality to endswith or a regex: https://github.com/ros-infrastructure/rosdistro/search?q=get_url_parts

**Comment by ayrton04** [comment]
Do you have a preference?

**Comment by mikepurvis** [comment]
Changing the domain to include the token as required seems less disruptive to me. The main thing is only including it when it's actually a token and avoiding the `git@` that comes along with SSH URLs.

**Comment by ayrton04** [comment]
Do we want to make it specific to the GH tokens, which are 40 hex characters? I think this should work:

```
(?:https?:\/\/|ssh:\/\/|git:\/\/|git@)(([a-fA-F0-9]{40}@)?[\w.-]+)[:/]([\w/-]*)(?:\.git)?$
```

**Comment by mikepurvis** [comment]
Fine by me. Obviously update the test accordingly so we know what's actually going on, and update the instances of `get_url_parts`.

**Comment by ayrton04** [comment]
:+1: Will do.
